web:
- https://docs.google.com/presentation/d/1fN0EjV0nLMeimXNYN851SFbheJQrczNhVFBPDWt0zwc/edit#slide=id.p


qa:
- https://docs.google.com/presentation/d/1S9qX4ziUnLO67YgjzLjUFJN6fE10SSP_fZ14xeuBWpo/edit#slide=id.g2610876e4b6_0_4

qa interview questions
1. DIFFERENTIATE	TEST CASES vs TEST SCENARIO
		
2. DIFFERENTIATE	MANUAL TESTING vs AUTOMATED TESTING	
		
3. WHAT IS REGRESSIONK TESTING?
		
4. HOW DO YOU PERFORM REGRESSION TESTING?	
		
5. HOW DO YOU MANAGE AND TRACK DEFECTS IN PROJECT?	
		
6. WHAT SORT OF SKILLS ARE NEEDED TO BE AN EFFECTIVE TESTER?
		
